apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-deployment
  labels:
    app: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep-container
        image: busybox
        command: ["sh", "-c", "sleep infinity"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"

